platan/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('generate-serial-numbers/', views.generate_serial_numbers_page, name='generate-serial-numbers'),
    path('stand-board-case/', views.stand_board_case_page, name='stand-board-case'),
    path('stand-package/', views.stand_package_page, name='stand-package'),
    path('stand-visual-inspection/', views.stand_visual_inspection_page, name='stand-visual-inspection'),
    path('stand-diagnostic/', views.stand_diagnostic_page, name='stand-diagnostic'),
    path('stand-pci/', views.stand_pci_page, name='stand-pci'),
    path('history/', views.hisory_page, name='history'),

    # ajax
    path('ajax/load-modifications/', views.load_modifications, name='ajax_load_modifications'),
    path('ajax/diagnostic-output/', views.diagnostic_load_output, name='ajax_diag_output'),
    path('ajax/pci-output/', views.pci_load_output, name='ajax_pci_output')
]

platan_web/urls.py
import django.contrib.auth
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('platan.urls')),
    path('', include('django.contrib.auth.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_URL) + static(settings.IMAGES_URL, document_root=settings.IMAGES_URL)

platan/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.


class GenerateSerialNumbers(models.Model):
    device_type = models.ForeignKey('DeviceType', on_delete=models.CASCADE)
    modification_type = models.ForeignKey('ModificationType', on_delete=models.CASCADE)
    detail_type = models.ForeignKey('DetailType', on_delete=models.CASCADE)
    place_of_production = models.ForeignKey('PlaceOfProduction', on_delete=models.CASCADE)
    count = models.IntegerField(default=1)


class DeviceType(models.Model):
    class Meta:
        verbose_name = 'Тип устройства'
        verbose_name_plural = 'Тип устройства'

    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class ModificationType(models.Model):
    class Meta:
        verbose_name = 'Тип модификации'
        verbose_name_plural = 'Тип модификации'

    name = models.CharField(max_length=40)
    device_type = models.ForeignKey(DeviceType, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class DetailType(models.Model):
    class Meta:
        verbose_name = 'Тип изделия'
        verbose_name_plural = 'Тип изделия'

    name = models.CharField(max_length=80)

    def __str__(self):
        return self.name


class PlaceOfProduction(models.Model):
    class Meta:
        verbose_name = 'Место производства'
        verbose_name_plural = 'Место производства'

    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

platan/forms.py
from django import forms
from .models import DeviceType, ModificationType, GenerateSerialNumbers
from django.core.exceptions import ValidationError
from .programs.db_2000 import *
from .programs.db_history import *


class HistoryForm(forms.Form):
    serial_number = forms.CharField(label='', max_length=14)
    
    def clean(self):
        super(HistoryForm, self).clean()

        serial_number = self.cleaned_data['serial_number']

        if len(serial_number) != 14:
            self.errors['serial_number'] = self.error_class(['Некорректный серийный номер'])
            return self.cleaned_data

        if not check_sn(engine, serial_number):
            self.errors['device_serial_number'] = self.error_class([f'{serial_number} отсутствует в Базе Данных"'])
            return self.cleaned_data
        return self.cleaned_data

class GenerateSerialNumbersForm(forms.ModelForm):
    """
    def __init__(self):
        super(GenerateSerialNumbersForm, self).__init__()
        self.fields['device_type'].label = 'Тип устройства'
        self.fields['device_type'].empty_label = 'Выберите устройство'

        self.fields['modification_type'].label = 'Тип модификации'
        self.fields['modification_type'].empty_label = 'Выберите модификацию'

        self.fields['detail_type'].label = 'Тип детали'
        self.fields['detail_type'].empty_label = 'Выберите деталь'

        self.fields['place_of_production'].label = 'Место производства'
        self.fields['place_of_production'].empty_label = 'Выберите место'

        self.fields['count'].label = 'Количество'

        self.fields['modification_type'].queryset = ModificationType.objects.none()
    """

    class Meta:
        model = GenerateSerialNumbers
        fields = '__all__'

        labels = {
            'device_type': 'Тип устройства',
            'modification_type': 'Тип модификации',
            'detail_type': 'Тип детали',
            'place_of_production': 'Место производства',
            'count': 'Количество',
        }


class ChainBoardCase(forms.Form):
    board_serial_number = forms.CharField(label='', max_length=14)
    case_serial_number = forms.CharField(label='', max_length=14)

    def clean(self):
        super(ChainBoardCase, self).clean()

        board_serial_number = self.cleaned_data.get('board_serial_number')
        case_serial_number = self.cleaned_data.get('case_serial_number')

        board_list = []
        case_list = []
        cut_board = board_serial_number[4:6]
        cut_case = case_serial_number[4:6]

        """if len(board_serial_number) < 14:
            self._errors['board_serial_number'] = self.error_class(['Неправильно указан серийный номер платы'])
        elif 'RS' not in board_serial_number[0:2:]:
            self._errors['board_serial_number'] = self.error_class(['Неправильно указан серийный номер платы'])"""

        if cut_board == '20':
            if cut_case == '10':
                if board_serial_number == case_serial_number:
                    self.errors['case_serial_number'] = self.error_class([f'Серийные номера платы и корпуса одинаковые!\nОтсканируйте заново'])
                else:
                    if len(board_serial_number) == 14:
                        check = check_sn_b(engine, board_serial_number)
                        if check:
                            self._errors['board_serial_number'] = self.error_class([f'Серийного номера {board_serial_number} нет в Базе Данных.\nОтсканируйте заново, в проивном случае верните плату на стенд диагностики.'])
                        else:
                            status = check_diag(engine, board_serial_number)
                            if str(status) == 'False':
                                self._errors['board_serial_number'] = self.error_class([f'Плата с серийным номером {board_serial_number} не прошла дигностику!\nВерните плату на стенд диагностики!'])
                            else:
                                board_list.append(board_serial_number)
                    else:
                        self._errors['board_serial_number'] = self.error_class([f'Серийный номер платы {board_serial_number} некорректный!\nОтсканируйте заново!'])

                    if len(board_list) == 1:
                        if len(case_serial_number) == 14:
                            check = check_sn_r(engine, case_serial_number)
                            if not check:
                                self.errors['case_serial_number'] = self.error_class([f'Серийный номер корпуса {case_serial_number} уже есть в БД!\nОтсканируйте заново!'])
                            else:
                                case_list.append(case_serial_number)
                        else:
                            self.errors['case_serial_number'] = self.error_class([f'Серийный номер корпуса {case_serial_number} некорректный! Отсканируйте заново!'])
                    else:
                        pass
            else:
                self.errors['case_serial_number'] = self.error_class([f'Серийный номер корпуса {case_serial_number} не соответствует серийному номеру корпуса!'])
        else:
            self.errors['board_serial_number'] = self.error_class([f'Серийный номер платы {board_serial_number} не соответствует серийному номеру платы!'])

        return self.cleaned_data


class StandPackage(forms.Form):
    device_serial_number = forms.CharField(label='', max_length=14)

    def clean(self):
        super(StandPackage, self).clean()

        device_serial_number = self.cleaned_data['device_serial_number']

        cut_device = device_serial_number[4:6]

        if cut_device == '10':
            if len(device_serial_number) == 14:
                check = check_sn_r(engine, device_serial_number)
                if check:
                    self.errors['device_serial_number'] = self.error_class([f'Серийный номер устройства {device_serial_number} отсутствует в Базе Данных"\nОтсканируйте заново.'])
                else:
                    date = check_date_time_pci(engine, device_serial_number)
                    if date == 'No':
                        self.errors['device_serial_number'] = self.error_class([f'Устройство с серийным номером {device_serial_number} не прошло ПСИ!\nПередайте устройство на стенд ПСИ!'])
            else:
                self.errors['device_serial_number'] = self.error_class([f'Серийный номер устройства некорректный!\nОтсканируйте заново!'])
        else:
            self.errors['device_serial_number'] = self.error_class([f'Серийный номер устройства {device_serial_number} не соответствует серийному номеру устройства!\nОтсканируйте повторно!'])

        return self.cleaned_data


class StandVisualInspection(forms.Form):
    board_serial_number = forms.CharField(label='', max_length=14)

    def clean(self):
        super(StandVisualInspection, self).clean()

        board_serial_number = self.cleaned_data['board_serial_number']

        if len(board_serial_number) == 14:
            if board_serial_number[4:6] == '20':
                if check_board_count(engine, board_serial_number):
                    self.errors['board_serial_number'] = self.error_class([f'Плата с серийным номером {board_serial_number} уже есть в Базе Данных!'])
            else:
                self.errors['board_serial_number'] = self.error_class([f'Серийный номер указан неправильно! Отсканируйте повторно.'])
        else:
            self.errors['board_serial_number'] = self.error_class([f'Серийный номер указан неправильно! Отсканируйте повторно.'])

        return self.cleaned_data


class StandDiagnostic(forms.Form):
    CHOICES_COUNT = zip(range(1,6), range(1, 6))
    CHOICES_TYPE = (
        ('RS', 'Сервисный маршрутизатор'),
        ('RB', 'Граничный маршрутизатор'),
    )

    diagnostic_device_type = forms.ChoiceField(choices=CHOICES_TYPE)
    board_count = forms.ChoiceField(choices=CHOICES_COUNT)
    # board_serial_number_1 = forms.CharField(max_length=14)
    board_serial_number_1 = forms.CharField(widget=forms.TextInput(), max_length=14)
    board_serial_number_2 = forms.CharField(widget=forms.TextInput(
        attrs={
            'maxlength': '14',
        }), required=False)
    board_serial_number_3 = forms.CharField(widget=forms.TextInput(
        attrs={
            'maxlength': '14',
        }), required=False)
    board_serial_number_4 = forms.CharField(widget=forms.TextInput(
        attrs={
            'maxlength': '14',
        }), required=False)
    board_serial_number_5 = forms.CharField(widget=forms.TextInput(
        attrs={
            'maxlength': '14',
        }), required=False)

    output = forms.CharField(widget=forms.Textarea(attrs={
        'style': 'resize:none;',
        'readonly': True,
    }), required=False)

    def clean(self):
        super(StandDiagnostic, self).clean()

        board_count = self.cleaned_data['board_count']

        board_serial_number_1 = self.cleaned_data['board_serial_number_1']
        board_serial_number_2 = self.cleaned_data['board_serial_number_2']
        board_serial_number_3 = self.cleaned_data['board_serial_number_3']
        board_serial_number_4 = self.cleaned_data['board_serial_number_4']
        board_serial_number_5 = self.cleaned_data['board_serial_number_5']

        if board_count == '1':
            if len(board_serial_number_1) == 14:
                if board_serial_number_1[4:6] == '20':
                    if check_board_in_db(engine, board_serial_number_1) == 0:
                        self.errors['board_serial_number_1'] = self.error_class([f'Плата с серийным номером {board_serial_number_1} отсутствует в Базе Данных!\nПередайте плату на стенд визуального осмотра.'])
                else:
                    self.errors['board_serial_number_1'] = self.error_class([f'Серийный номер указан неправильно!\nОтсканируйте повторно.'])
            else:

platan/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Добавление дополнительного статического CSS файла -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script type="text/javascript" src="{{ STATIC_URL }} /static/js/jquery-3.6.0.min.js"></script>
</head>

<body>
    <div class="header-container">
        <div class="left-header">

        </div>

        <div class="middle-header">
            <div align="center" id="header-middle-title"><b>{% block page_name %}{% endblock %}</b></div>
        </div>

        <div class="right-header">
            {% if user.is_authenticated %}
                <div align="right"><a class="username" href="">Имя пользователя: {{ user.get_username }}</a></div>
                <div align="right"><a class="logout" href="{% url 'logout'%}">Выход</a></div>
            {% else %}
                <div align="right"><a class="login" href="{% url 'login' %}">Авторизация</a></div>
            {% endif %}
        </div>
    </div>

    <div class="content-container">
        {% if user.is_authenticated %}
            <div class="left">
                <form class="menu">
                    <ul id="navigation" class="sidebar">
                        {% if request.path == '/' %}
                            <li><a class="active" href="{% url 'index' %}">Главная страница</a></li>
                        {% else %}
                            <li><a href="{% url 'index' %}">Главная страница</a></li>
                        {% endif %}

                        {% if request.path == '/generate-serial-numbers/' %}
                            <li><a class="active" href="{% url 'generate-serial-numbers' %}">Генерация серийных номеров</a></li>
                        {% else %}
                            <li><a href="{% url 'generate-serial-numbers' %}">Генерация серийных номеров</a></li>
                        {% endif %}

                        {% if request.path == '/stand-visual-inspection/' %}
                            <li><a class="active" href="{% url 'stand-visual-inspection' %}">Стенд визуального осмотра</a></li>
                        {% else %}
                            <li><a href="{% url 'stand-visual-inspection' %}">Стенд визуального осмотра</a></li>
                        {% endif %}

                        {% if request.path == '/stand-diagnostic/' %}
                            <li><a class="active" href="{% url 'stand-diagnostic' %}">Стенд диагностики</a></li>
                        {% else %}
                            <li><a href="{% url 'stand-diagnostic' %}">Стенд диагностики</a></li>
                        {% endif %}

                        {% if request.path == '/stand-board-case/' %}
                            <li><a class="active" href="{% url 'stand-board-case' %}">Стенд сборки</a></li>
                        {% else %}
                            <li><a href="{% url 'stand-board-case' %}">Стенд сборки</a></li>
                        {% endif %}

                        {% if request.path == '/stand-pci/' %}
                            <li><a class="active" href="{% url 'stand-pci' %}">Стенд ПСИ</a></li>
                        {% else %}
                            <li><a href="{% url 'stand-pci' %}">Стенд ПСИ</a></li>
                        {% endif %}

                        {% if request.path == '/stand-package/' %}
                            <li><a class="active" href="{% url 'stand-package' %}">Стенд упаковки</a></li>
                        {% else %}
                            <li><a href="{% url 'stand-package' %}">Стенд упаковки</a></li>
                        {% endif %}

                        {% if user.is_superuser %}
                        {% if request.path == '/history/' %}
                            <li><a class="active" href="{% url 'history' %}">История девайса</a></li>
                        {% else %}
                            <li><a href="{% url 'history' %}">История девайса</a></li>
                        {% endif %}
                        {% endif %}
                    </ul>
                </form>
            </div>
        {% else %}
            <div class="left-logout">

            </div>
        {% endif %}

        <div class="middle" align="center">
            {% block middle %}
            {% endblock %}
        </div>

        <div class="right">

        </div>
    </div>

</body>
</html>

platan/templates/board_case.html
{% extends "base_generic.html" %}

{% block title %}
{% load static %}
<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
<title>Стенд плата-корпус</title>
{% endblock %}

{% block page_name %}<div align="center">Стенд плата-корпус</div>{% endblock %}

{% block content-blocks %}

<div class="left" id="board-case-left">

</div>

<div class="middle" id="board-case-middle">
    <form method="post">
        {% csrf_token %}
        <div align="center">Отсканируйте серийный номер платы</div>
        {{ form.board_serial_number }}
        {{ form.board_serial_number.errors }}
        <div align="center">Отсканируйте серийный номер корпуса</div>
        {{ form.case_serial_number }}
        {{ form.case_serial_number.errors }}
        <button type="submit" id="board-case-chain" name="submit_btn">Привязать</button>
    </form>
</div>

<div class="right" id="board-case-right">

</div>

{% endblock %}

platan/templates/generate_serial_numbers.html
{% extends "base_generic.html" %}

{% block title %}
{% load static %}
<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
<title>Генерация серийных номеров</title>
{% endblock %}

{% block page_name %}<div align="center">Генерация серийных номеров</div>{% endblock %}

{% block middle %}
<form method="post" id="generateSerialNumbers" data-modifications-url="{% url 'ajax_load_modifications' %}">
    {% csrf_token %}
    <div class="generate-serial-numbers-label">Тип устройства</div>
    {{ form.device_type }}
    <div class="generate-serial-numbers-label">Тип модификации</div>
    {{ form.modification_type }}
    <div class="generate-serial-numbers-label">Тип детали</div>
    {{ form.detail_type }}
    <div class="generate-serial-numbers-label">Место производства</div>
    {{ form.place_of_production }}
    <div class="generate-serial-numbers-label">Количество</div>
    {{ form.count }}
    <div class="generate-serial-numbers-label"><button type="submit" id="generate-serial-numbers-button" class="save btn btn-default" name="submit_btn">Сгенерировать</button></div>
</form>

    <script>
        window.onload = function clearModificationCheckBox()
        {
            let html_data = '<option value="">---------</option>';
            $("#id_modification_type").html(html_data);

        }
    </script>

    <script>
        $("#id_device_type").change(function () {
            const url = $("#generateSerialNumbers").attr("data-modifications-url");  // get the url of the `load_modifications` view
            const device_typeId = $(this).val();  // get the selected device_type ID from the HTML input

            if (device_typeId == '')
            {
                search_id = 0;
            }
            else
            {
                search_id = device_typeId;
            }

            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= /ajax/load-modifications/ )
                data: {
                    'device_type_id': search_id // device_typeId        add the device_type id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_modifications` view function
                    $("#id_modification_type").html(data);  // replace the contents of the modification input with the data that came from the server
                    /*

                    let html_data = '<option value="">---------</option>';
                    data.forEach(function (modification_type) {
                        html_data += `<option value="${modification_type.id}">${modification_type.name}</option>`
                    });
                    // console.log(html_data);
                    $("#id_modification_type").html(html_data);

                    */
                }
            });

        });
    </script>
</div>

<div class="right">

</div>

{% endblock %}

platan/templates/history.html
{% extends "base_generic.html" %}

{% block title %}
{% load static %}
<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
{% load static %}

<title>Генерация серийных номеров</title>
{% endblock %}

{% block page_name %}<div align="center">История девайса</div>{% endblock %}

{% block middle %}
<form method="post" id="generateSerialNumbers" data-modifications-url="{% url 'ajax_load_modifications' %}">
    {% csrf_token %}
    <div class="generate-serial-numbers-label">Серийный номер</div>
    {{ form.serial_number }}
    <br>
    <br>
    <div class="generate-serial-numbers-label"><button type="submit" id="generate-serial-numbers-button" class="save btn btn-default" name="submit_btn">Поиск</button></div></form>
    <br>
{% if history %}
<table bgcolor=#6767e1 border="1" width="80%">
<caption >История</caption>
    <br>
    <tr>
    <th>id</th>
    <th>Сообщение</th>
    <th>Дата/Время</th>
    </tr>
    {% for data in history %}
    <tr><td>{{ data.0 }}</td><td>{{ data.1 }}</td><td>{{ data.2 }}</td>
    {% endfor %}
</table>
{% endif %}
{% endblock %}

platan/templates/stand-diagnostic.html
{% extends "base_generic.html" %}

{% block title %}
{% load static %}
<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
<title>Стенд диагностики</title>
{% endblock %}

{% block page_name %}<div align="center">Стенд диагностики</div>{% endblock %}

{% block middle %}
<form method="post" id="diagnostic-form">
    {% csrf_token %}
    <div id="diag-left-frame">
        <div align="center"><b>Выберите тип устройства</b></div>
        {{ form.diagnostic_device_type }}
        <div align="center"><b>Выберите количество устройств</b></div>
        {{ form.board_count }}
        <div class="board-serial-numbers">
            <div align="right" id="board-container-1">
                <div align="center" class="tooltip">
                    <img class="info-image" align="center" src="/images/info.png" width="3%">
                    <span class="tooltiptext">
                        <img class="frame" width="800%" src="/images/board_1.jpg">
                    </span>
                </div>
                {{ form.board_serial_number_1 }}
                <div align="left" class="errors" id="board_serial_number_1_error">{{ form.board_serial_number_1.errors.as_text }}</div>
            </div>
            <div align="right" id="board-container-2">
                <div align="center" class="tooltip">
                    <img class="info-image" align="center" src="/images/info.png" width="3%">
                    <span class="tooltiptext">
                        <img  class="frame" width="800%" src="/images/board_1.jpg">
                    </span>
                </div>
                {{ form.board_serial_number_2 }}
                <div align="left" class="errors" id="board_serial_number_2_error">{{ form.board_serial_number_2.errors.as_text }}</div>
            </div>
            <div align="right" id="board-container-3">
                <div align="center" class="tooltip">
                    <img class="info-image" align="center" src="/images/info.png" width="3%">
                    <span class="tooltiptext">
                        <img class="frame" width="800%" src="/images/board_1.jpg">
                    </span>
                </div>
                {{ form.board_serial_number_3 }}
                <div align="left" class="errors" id="board_serial_number_3_error">{{ form.board_serial_number_3.errors.as_text }}</div>
            </div>
            <div align="right" id="board-container-4">
                <div align="center" class="tooltip">
                    <img class="info-image" align="center" src="/images/info.png" width="3%">
                    <span class="tooltiptext">
                        <img class="frame" width="800%" src="/images/board_1.jpg">
                    </span>
                </div>
                {{ form.board_serial_number_4 }}
                <div align="left" class="errors" id="board_serial_number_4_error">{{ form.board_serial_number_4.errors.as_text }}</div>
            </div>
            <div align="right" id="board-container-5">
                <div align="center" class="tooltip">
                    <img class="info-image" align="center" src="/images/info.png" width="3%">
                    <span class="tooltiptext">
                        <img class="frame" width="800%" src="/images/board_1.jpg">
                    </span>
                </div>
                {{ form.board_serial_number_5 }}
                <div align="left" class="errors" id="board_serial_number_5_error">{{ form.board_serial_number_5.errors.as_text }}</div>
            </div>
        </div>
        <button type="submit" name="diagnostic_start" id="btn_diagnostic_start">Старт Диагностики</button>
        </div>

    <div align="center" id="diag-right-frame">
        <b>Окно вывода</b>
        {{ form.output }}
    </div>
</form>

<script>
    function clearErrors() {
        $('#board_serial_number_1_error').remove();
        $('#board_serial_number_2_error').remove();
        $('#board_serial_number_3_error').remove();
        $('#board_serial_number_4_error').remove();
        $('#board_serial_number_5_error').remove();
    }
</script>

<script>
    $('#btn_diagnostic_start').click(clearErrors);
</script>

<script>
    function UpdateEntries() {
        var selectedCount = $('#id_board_count').val();

        if(selectedCount == 1)
        {
            $('#board-container-2').attr('hidden', '');
            $('#board-container-3').attr('hidden', '');
            $('#board-container-4').attr('hidden', '');
            $('#board-container-5').attr('hidden', '');
            $('#id_board_serial_number_2').removeAttr('required', '');
            $('#id_board_serial_number_3').removeAttr('required', '');
            $('#id_board_serial_number_4').removeAttr('required', '');
            $('#id_board_serial_number_5').removeAttr('required', '');
            $('#id_board_serial_number_2').val('')
            $('#board_serial_number_2_error').html('')
            $('#id_board_serial_number_3').val('')
            $('#board_serial_number_3_error').html('')
            $('#id_board_serial_number_4').val('')
            $('#board_serial_number_4_error').html('')
            $('#id_board_serial_number_5').val('')
            $('#board_serial_number_5_error').html('')
        }
        else if(selectedCount == 2)
        {
            $('#id_board_serial_number_2').attr('required', '');
            $('#board-container-2').removeAttr('hidden');
            $('#board-container-3').attr('hidden', '');
            $('#board-container-4').attr('hidden', '');
            $('#board-container-5').attr('hidden', '');
            $('#id_board_serial_number_3').val('')
            $('#board_serial_number_3_error').html('')
            $('#id_board_serial_number_4').val('')
            $('#board_serial_number_4_error').html('')
            $('#id_board_serial_number_5').val('')
            $('#board_serial_number_5_error').html('')
        }
        else if(selectedCount == 3)
        {
            $('#id_board_serial_number_2').attr('required', '');
            $('#id_board_serial_number_3').attr('required', '');
            $('#board-container-2').removeAttr('hidden');
            $('#board-container-3').removeAttr('hidden');
            $('#board-container-4').attr('hidden', '');
            $('#board-container-5').attr('hidden', '');
            $('#id_board_serial_number_4').val('')
            $('#board_serial_number_4_error').html('')
            $('#id_board_serial_number_5').val('')
            $('#board_serial_number_5_error').html('')
        }
        else if(selectedCount == 4)
        {
            $('#id_board_serial_number_2').attr('required', '');
            $('#id_board_serial_number_3').attr('required', '');
            $('#id_board_serial_number_4').attr('required', '');
            $('#board-container-2').removeAttr('hidden');
            $('#board-container-3').removeAttr('hidden');
            $('#board-container-4').removeAttr('hidden');
            $('#board-container-5').attr('hidden', '');
            $('#id_board_serial_number_5').val('')
            $('#board_serial_number_5_error').html('')
        }
        else if(selectedCount == 5)
        {
            $('#id_board_serial_number_2').attr('required', '');
            $('#id_board_serial_number_3').attr('required', '');
            $('#id_board_serial_number_4').attr('required', '');
            $('#id_board_serial_number_5').attr('required', '');
            $('#board-container-2').removeAttr('hidden');
            $('#board-container-3').removeAttr('hidden');
            $('#board-container-4').removeAttr('hidden');
            $('#board-container-5').removeAttr('hidden');
        }
    }
</script>

<script>
    $(document).ready(UpdateEntries);
</script>

<script>
    $('#id_board_count').on('change', UpdateEntries);
</script>

<script>
    function refresh_data() {
        $.ajax({
            url: '{% url "ajax_diag_output" %}',
            success: function(data) {
                $('#id_output').html(data),
                setTimeout(refresh_data, 1000);
            }
        });
    }

    $(function(){
        refresh_data();
    });
</script>

{% endblock %}

platan/templates/stand_package.html
{% extends "base_generic.html" %}

{% block title %}
{% load static %}
<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
<title>Стенд упаковки</title>
{% endblock %}

{% block page_name %}<div align="center">Стенд упаковки</div>{% endblock %}

{% block middle %}
<form method="post">
    {% csrf_token %}
    <div align="center">
        Отсканируйте серийный номер изделия
        <div align="center" class="tooltip">
        <img class="info-image" align="center" src="/images/info.png" width="3%">
        <span class="tooltiptext">
        <img class="frame" width="600" src="/images/sticker_1.jpg">
        </span>
        </div>
    </div>
    <div id="board-serial-number-container">
        {{ form.device_serial_number }}
        <div align="left" class="errors" id="device-serial-number-error">
            {{ form.device_serial_number.errors.as_text }}
        </div>
    </div>
    <button type="submit" id="btn_device_package" name="submit_btn">Начать</button>
</form>

{% endblock %}